version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.4
  aws-ecr: circleci/aws-ecr@1.0.0
  aws-ecs: circleci/aws-ecs@0.0.6
jobs:
  build:
    - aws-ecr/build_image:
      account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      repo: "${AWS_ECR_REPOSITORY_NAME}"
      tag: "${CIRCLE_SHA1}"
  deploy:
    steps:
      - aws-cli/configure:
          aws-access-key-id: "${AWS_ACCESS_KEY_ID}"
          aws-region: "${AWS_REGION}"
      - run:
          name: ECR login
          command: |
            eval $(aws ecr get-login --region $AWS_REGION --registry-ids $AWS_ACCOUNT_ID --no-include-email)
      - aws-ecr/push_image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
          repo: "${AWS_ECR_REPOSITORY_NAME}"
          tag: "${CIRCLE_SHA1}"
workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
